# Generated by Django 5.1.3 on 2024-11-17 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.TextField()),
                ('descripcion_categoria', models.TextField(blank=True, null=True)),
                ('activo_categoria', models.BooleanField(default=True)),
                ('relevancia_categoria', models.IntegerField(default=0)),
                ('fecha_creacion_categoria', models.DateTimeField(auto_now_add=True)),
                ('actualizacion_categoria', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_cliente', models.TextField()),
                ('nombre_cliente', models.TextField()),
                ('informacion_cliente', models.TextField(blank=True, null=True)),
                ('correo_cliente', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono_cliente', models.TextField(blank=True, null=True)),
                ('direccion_cliente', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.TextField()),
                ('informacion_proveedor', models.TextField(blank=True, null=True)),
                ('correo_proveedor', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono_proveedor', models.TextField(blank=True, null=True)),
                ('direccion_proveedor', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.TextField()),
                ('pvp_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_producto', models.IntegerField()),
                ('minimo_producto', models.IntegerField(default=0)),
                ('maximo_producto', models.IntegerField(default=100)),
                ('fecha_ingreso_producto', models.DateTimeField(auto_now_add=True)),
                ('estado_producto', models.CharField(choices=[('Disponible', 'Disponible'), ('Reservado', 'Reservado'), ('Agotado', 'Agotado')], default='Disponible', max_length=20)),
                ('descripcion_producto', models.TextField(blank=True, null=True)),
                ('marca_producto', models.TextField(blank=True, null=True)),
                ('ultima_venta_producto', models.DateTimeField(blank=True, null=True)),
                ('categoria_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimientoInventario', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=10)),
                ('cantidad_movimientoInventario', models.IntegerField()),
                ('fecha_movimientoInventario', models.DateTimeField(auto_now_add=True)),
                ('motivo_movimientoInventario', models.TextField(blank=True, null=True)),
                ('producto_movimientoInventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_lote', models.IntegerField()),
                ('fecha_ingreso_lote', models.DateTimeField(auto_now_add=True)),
                ('fecha_caducidad_lote', models.DateField(blank=True, null=True)),
                ('producto_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_productoProveedor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_entrega_productoProveedor', models.IntegerField(blank=True, help_text='Días para entrega', null=True)),
                ('porducto_productoProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('proveedor_productoProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedores_producto',
            field=models.ManyToManyField(through='inventario.ProductoProveedor', to='inventario.proveedor'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('total_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_venta', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Cancelado'), ('F', 'Finalizado')], default='P', max_length=1)),
                ('metodo_venta', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_articuloVenta', models.IntegerField()),
                ('pvp_articuloVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_articuloVenta', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('producto_articuloVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('venta_articuloVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.venta')),
            ],
        ),
    ]
